# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46425bbd5cb36b364e7ebb5bdaa87488acf407bc0d5e00ba38269b7818f12ac776941b864c245f365114098fef7c092074b5fa9fe6a0b3f67d431a8edb920d2a

test:
  secret_key_base: 5e859ba4a357f407d02276db04c8b85d8e7d99046b4e92294113ffe22ddcd9ee75d9cfb98eede7842a6bf2c92c0a4fe67c05671b5a085df4b6ae4cb527246576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
